### PR TITLE
fix export and upload csv bugs

### LINKED ISSUE #83: Fix Export & Upload CSV bugs
Please fix bugs 4 and 14 on the [dogfooding doc](https://docs.google.com/document/d/12VIkn9-iet9nRUiLaQjT_Y9oR2ggOaREwxJ4twXSYjo/edit#)

### LINKED ISSUE #117: Upload CSV Pagination
- Use pagination to display the rows when uploading a CSV

### PR DESCRIPTION
**Pull request by ctc-devops**
Please fix bugs 4 and 14 on the [dogfooding doc](https://docs.google.com/document/d/12VIkn9-iet9nRUiLaQjT_Y9oR2ggOaREwxJ4twXSYjo/edit#)
closes #83

### CODE REVIEW

File: src/components/UploadCSV/UploadCSVUtils.jsx [hunk 1]
```diff
@@ -1,10 +1,33 @@
...
+//     const { path, createError } = this;
+//     return isValidZip(value) ? true : createError({ path, message: 'Invalid zip code' });
+//   });
+// }
+
+function validateZipcodeInCountry() {
+  return this.test('isZipInCountry', function zipcodeAndCountryCheck({ zipCode, country }) {
     const { path, createError } = this;
-    return isValidZip(value) ? true : createError({ path, message: 'Invalid zip code' });
+    console.log(zipCode, country);
```
Comment (ctc-devops) [inline src/components/UploadCSV/UploadCSVUtils.jsx]: ⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

File: src/components/UploadCSV/UploadCSVUtils.jsx [hunk 2]
```diff
@@ -24,7 +24,7 @@ export default yup
   .object({
     boxNumber: yup.number().boxNotExists().required().typeError('Missing or invalid box number'),
     date: yup.date().required().typeError('Missing or invalid date'),
-    zipCode: yup.string().isZip().required('Missing or invalid zip code'),
+    zipCode: yup.string().isZip().required('Missing zip code'),
```
Comment (jeffcheema) [inline src/components/UploadCSV/UploadCSVUtils.jsx]: If I recall correctly you can also do this: 
`yup.string().isZip('Invalid Zip Code').required('Missing zip code')`
Just suggesting that since in the last commit the error comment was 'Missing or invalid zip code'

**Review by jeffcheema — COMMENTED** [review]
Just a small comment on the UploadCSVUtils.jsx file :sweat_smile:  
Other than that LGTM! :1st_place_medal:

File: src/components/ExportCSV/ExportCSVRow/ExportCSVRow.module.css [hunk 3]
```diff
@@ -8,4 +8,11 @@
...
-}
\ No newline at end of file
+}
+
+.green-check-icon,
+.red-cross-icon {
+  position: absolute;
+  left: 80px;
+  top: 40%;
+}
```
Comment (meghakak) [inline src/components/ExportCSV/ExportCSVRow/ExportCSVRow.module.css:18]: Is this styling being applied? It doesn't look centered on my screen.
image

File: src/components/UploadCSVView/CSVViewTable/CSVViewTable.module.css [hunk 4]
```diff
@@ -17,7 +17,7 @@
 .csv-table-container {
   display: flex;
   flex-direction: column;
-  height: 80vh;
+  height: 65vh;
```
Comment (meghakak) [inline src/components/UploadCSVView/CSVViewTable/CSVViewTable.module.css:20]: Could we ask design if it's possible to move the Add to Map button to the top of the page instead? The button is still cut off on my screen :(

**Review by meghakak — CHANGES_REQUESTED** [review]
The code looks fine, but I'm still getting the same styling errors on my end :( Could you test the styling on different screen sizes?

File: src/components/UploadCSVView/CSVViewTable/CSVViewTable.module.css (hunk 4 above)
Comment (Preston-Young) [reply src/components/UploadCSVView/CSVViewTable/CSVViewTable.module.css:20]: Yeah let's ask them

File: src/components/AddBoxForm/AddBoxForm.jsx [hunk 5]
```diff
@@ -88,7 +88,7 @@ const AddBoxForm = () => {
     const [latitude, longitude] = await getLatLong(formData.zipcode, formData.country);
     if (latitude === undefined && longitude === undefined) {
       // TODO: display toast component
-      alert(`Cannot find ${formData.zipcode} in country ${formData.country}`);
+      console.log(`Cannot find ${formData.zipcode} in country ${formData.country}`);
```
Comment (ctc-devops) [inline src/components/AddBoxForm/AddBoxForm.jsx:91]: ⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

File: src/components/UploadCSV/UploadCSV.jsx [hunk 6]
```diff
@@ -80,30 +113,72 @@ const UploadCSV = ({ isOpen, onClose }) => {
...
+      // find lat/long for each formData
+      const allCoordinates = await Promise.all(
+        formDatas.map(async formData => getLatLong(formData.zipCode, formData.country)),
+      );
+
+      let hasError = false;
+      formDatas.forEach((formData, index) => {
+        if (allCoordinates[index].length === 0) {
+          // if lat/long is not found for this zipcode
+          alert('Cannot find latitude/longitude for zipcode. Please click Edit/View file');
```
Comment (ctc-devops) [inline src/components/UploadCSV/UploadCSV.jsx]: ⚠️ **[eslint]** <[no-alert](https://eslint.org/docs/rules/no-alert)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert.

File: src/components/UploadCSV/UploadCSV.jsx [hunk 7]
```diff
@@ -80,30 +113,72 @@ const UploadCSV = ({ isOpen, onClose }) => {
...
+        //     error,
+        //     latitude,
+        //     longitude,
+        //   }
+        // ]
+        setIsLoading(false);
+        navigate('/admin');
+      }
+    } catch (err) {
+      console.log(err);
```
Comment (ctc-devops) [inline src/components/UploadCSV/UploadCSV.jsx:165]: ⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

File: src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx [hunk 8]
```diff
@@ -41,93 +149,147 @@ const CSVViewTable = ({ rows }) => {
...
+        // find lat/long for each formData
+        const allCoordinates = await Promise.all(
+          formDatas.map(async formData => getLatLong(formData.zipCode, formData.country)),
+        );
+
+        let hasError = false;
+        formDatas.forEach((formData, index) => {
+          if (allCoordinates[index].length === 0) {
+            // if lat/long is not found for this zipcode
+            console.log('cannot find latitude for formData: ', formData);
```
Comment (ctc-devops) [inline src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx:210]: ⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

File: src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx [hunk 9]
```diff
@@ -41,93 +149,147 @@ const CSVViewTable = ({ rows }) => {
...
+        // });
+
+        // if none of the rows have any errors
+        if (!hasError) {
+          await FYABackend.post('/anchorBox/boxes', formDatas);
+          setIsLoading(false);
+          navigate('/admin');
+        }
+      } catch (err) {
+        console.log(err);
```
Comment (ctc-devops) [inline src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx:229]: ⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

**Review by jeffcheema — DISMISSED** [review]
LGTM!

File: src/components/UploadCSV/UploadCSV.jsx [hunk 10]
```diff
@@ -2,8 +2,9 @@ import React, { useState, useEffect } from 'react';
 import { useNavigate } from 'react-router-dom';
 import { v4 as uuidv4 } from 'uuid';
 import { usePapaParse } from 'react-papaparse';
+// import { PromisePool } from '@supercharge/promise-pool';
```
Comment (meghakak) [inline src/components/UploadCSV/UploadCSV.jsx]: nit: please remove

File: src/components/UploadCSV/UploadCSV.jsx (hunk 6 above)
Comment (meghakak) [inline src/components/UploadCSV/UploadCSV.jsx]: Please add a TODO here to replace this with a toast component

File: src/components/UploadCSV/UploadCSV.jsx [hunk 11]
```diff
@@ -80,30 +113,72 @@ const UploadCSV = ({ isOpen, onClose }) => {
...
+      );
+
+      let hasError = false;
+      formDatas.forEach((formData, index) => {
+        if (allCoordinates[index].length === 0) {
+          // if lat/long is not found for this zipcode
+          alert('Cannot find latitude/longitude for zipcode. Please click Edit/View file');
+          hasError = true;
+          setIsLoading(false);
+          // editRow(e, formData);
```
Comment (meghakak) [inline src/components/UploadCSV/UploadCSV.jsx]: nit: remove?

File: src/components/UploadCSV/UploadCSVUtils.jsx [hunk 12]
```diff
@@ -1,30 +1,66 @@
...
+    }
+    // if both zip code and country fields are not empty
+    if (zipCode && country) {
+      // the postal-codes-js library checks if zipcode is in the valid postal code format for the country
+      const isValidMessage = postalCodes.validate(countryCode, zipCode);
+      if (isValidMessage !== true) {
+        return createError({ path, message: `Cannot find ${zipCode} in this country` });
+      }
+
+      // check if Nominatim API can find lat/long for zipcode
```
Comment (meghakak) [inline src/components/UploadCSV/UploadCSVUtils.jsx]: Can you add a comment here explaining that nominatim API only allows 1 request/second so this will be replaced with the data dump instead?

File: src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx [hunk 13]
```diff
@@ -41,93 +149,147 @@ const CSVViewTable = ({ rows }) => {
...
+            formDatas[index].longitude = long;
+          }
+        });
+
+        // set lat/long for each formData
+        // formDatas.forEach((formData, index) => {
+        //   const [lat, long] = allCoordinates[index];
+        //   formDatas[index].latitude = lat;
+        //   formDatas[index].longitude = long;
+        // });
```
Comment (meghakak) [inline src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx]: nit: remove? since we are doing this in the previous forEach statement

File: src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx [hunk 14]
```diff
@@ -41,93 +149,147 @@ const CSVViewTable = ({ rows }) => {
...
             </Tr>
           </Thead>
           <Tbody>
-            {formDatas.map(data => {
+            {page.map((rowData, index) => {
+              prepareRow(rowData);
               return (
-                <Fragment key={data.id}>
-                  {editId === data.id ? (
+                <Fragment key={rowData.original.id}>
```
Comment (meghakak) [inline src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx:270]: Not sure if this is the right area to look in but when I upload a CSV file with no errors and then click on "Edit/View File", I'm not able to edit any of the rows. When I click on the pencil icon, it changes to an editable row, waits 1 second, and then reverts back to uneditable row. Could y'all look into why this is happening?

Comment (meghakak) [reply src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx:270]: For more context - I uploaded a CSV file with no errors except the lat/long couldn't be found

Comment (meghakak) [reply src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx:270]: Seems like this actually happens any time the row has no errors and the user clicks the pencil icon. For this case, the user should still be able to edit the row even if there are no errors.

**Review by meghakak — CHANGES_REQUESTED** [review]
This PR is insanely goated, y'all should be _very_ proud of yourselves! Thank you for all your hard work on this challenging feature :3 Left a few comments here, lmk if y'all have any questions about them.

File: src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx (hunk 13 above)
Comment (aliu55) [reply src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx]: yes yes

File: src/components/UploadCSV/UploadCSV.jsx (hunk 6 above)
Comment (aliu55) [reply src/components/UploadCSV/UploadCSV.jsx:135]: yeppppppppp

File: src/components/UploadCSV/UploadCSV.jsx (hunk 10 above)
Comment (aliu55) [reply src/components/UploadCSV/UploadCSV.jsx]: :worry-frog-cheer:

File: src/components/UploadCSV/UploadCSV.jsx (hunk 11 above)
Comment (aliu55) [reply src/components/UploadCSV/UploadCSV.jsx]: :worry-frog-cheer:

File: src/components/UploadCSV/UploadCSVUtils.jsx (hunk 12 above)
Comment (aliu55) [reply src/components/UploadCSV/UploadCSVUtils.jsx]: 🐸

File: src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx (hunk 14 above)
Comment (aliu55) [reply src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx:270]: Fixed in [145-upload-csv-high-fidelity-mobile-view](https://github.com/ctc-uci/find-your-anchor-frontend/tree/145-upload-csv-high-fidelity-mobile-view)!

**Review by meghakak — APPROVED** [review]
LGTM
