### PR TITLE
all admin general bugs

### LINKED ISSUE #190: Fix All General & Admin Dashboard Bugs
- Fix All General & Admin Dashboard Bugs
- Make sure that everything matches the Figma

### PR DESCRIPTION
**Pull request by ctc-devops**
- Fix All General & Admin Dashboard Bugs
- Make sure that everything matches the Figma
closes #190

### CODE REVIEW

File: src/components/Map/Map.jsx [hunk 1]
```diff
@@ -59,11 +58,14 @@ const Map = ({
...
-  // This function makes it so that when a marker cluser is clicked, the right side bar closes.
-  const handleMarkerClusterClicked = () => {
+  // This function makes it so that when a marker cluster is clicked, the right side bar closes.
+  const handleMarkerClusterClicked = cluster => {
+    // console.log(cluster.sourceTarget.getAllChildMarkers());
+    closeMarkerInfo();
     setSelectedCountry(null);
     setSelectedZipCode(null);
     setSelectedBox(null);
+    console.log(cluster);
```
Comment (ctc-devops) [inline src/components/Map/Map.jsx]: ⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

**Comment by claudeisakeeb** [comment]
As discussed we're leaving the marker clusters as is. Also we made a decision to just keep the cluster styling as is because
 1. we can't make it look like the tooltip thing in the Figma and 
 2. teal on white looks way worse than white on teal (just trust us)

File: src/common/utils.jsx [hunk 2]
```diff
@@ -18,9 +18,9 @@ FYABackend.interceptors.response.use(
     console.error(`[Axios] FYABackend error: ${JSON.stringify(error.toJSON(), null, 2)}`);
 
     // Redirect to internal server error page for 500 errors.
-    if (error.toJSON().status === 500) {
-      window.location.href = '/500';
-    }
+    // if (error.toJSON().status === 500) {
+    //   window.location.href = '/500';
+    // }
```
Comment (aliu55) [inline src/common/utils.jsx]: Please uncomment this

**Review by aliu55 — CHANGES_REQUESTED** [review]
Code review from me and Megha:

Good job on this sprint! We noticed that Bug 30 is marked as Not a Bug, but we still saw an x button on the box details in the mobile view. Could we please remove the x button? Also for Bug 59, it's marked as fixed but the rejected image still shows up in right sidebar. Could y'all look into this?

**Review by meghakak — CHANGES_REQUESTED** [review]
^^

File: src/common/utils.jsx (hunk 2 above)
Comment (jennymylee) [reply src/common/utils.jsx]: thank you for this

**Review by meghakak — APPROVED** [review]
LGTM

**Review by aliu55 — APPROVED** [review]
LGTM
