### PR TITLE
fix auth bugs

### LINKED ISSUE #112: Fix Auth Dogfooding Bugs
Please fix bugs 22 and 23 on the [dogfooding doc](https://docs.google.com/document/d/12VIkn9-iet9nRUiLaQjT_Y9oR2ggOaREwxJ4twXSYjo/edit#)

### PR DESCRIPTION
**Pull request by ctc-devops**
Please fix bugs 22 and 23 on the [dogfooding doc](https://docs.google.com/document/d/12VIkn9-iet9nRUiLaQjT_Y9oR2ggOaREwxJ4twXSYjo/edit#)
closes #112

### CODE REVIEW

File: src/components/Login/LoginForm.jsx [hunk 1]
```diff
@@ -47,8 +46,8 @@ const LoginForm = ({ cookies, redirectLink }) => {
     try {
       await logInWithEmailAndPassword(e.email, e.password, '/', navigate, cookies);
     } catch (err) {
-      setErrorMessage(err.message);
-      console.log(errorMessage);
+      // TODO: replace this with toast component
+      console.log(err.message);
```
Comment (ctc-devops) [inline src/components/Login/LoginForm.jsx:50]: ⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

**Review by claudeisakeeb — APPROVED** [review]
cool

**Review by sylvesteryue — APPROVED** [review]
LGTM sheeesh
