### PR TITLE
fix upload csv bugs

### LINKED ISSUE #176: Pick 3 Bugs from Upload CSV
- pick 3 bugs to fix for Upload CSV from the [Find You Bugs](https://docs.google.com/document/d/1f3dqxzRCiNGZ2yWU_FtyrNNjUOFZ8lxiEuXo958NVDM/edit#heading=h.57deawcull14) doc
- comment the 3 bugs fixed in the PR comments

### PR DESCRIPTION
**Pull request by ctc-devops**
- pick 3 bugs to fix for Upload CSV from the [Find You Bugs](https://docs.google.com/document/d/1f3dqxzRCiNGZ2yWU_FtyrNNjUOFZ8lxiEuXo958NVDM/edit#heading=h.57deawcull14) doc
- comment the 3 bugs fixed in the PR comments
closes #176

### CODE REVIEW

File: src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx [hunk 1]
```diff
@@ -316,11 +320,20 @@ const CSVViewTable = ({ rows, boxNumberMap }) => {
...
+            //   setEditId(null);
+            //   setAccordionProps({ allowToggle: true });
+            // }
+          }}
+        >
           <Flex flexDirection="column" gap="20px">
             {page.map((rowData, index) => {
               prepareRow(rowData);
               console.log(rowData);
+              console.log('Accordion Props: ', accordionProps);
```
Comment (ctc-devops) [inline src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx]: ⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

**Comment by Preston-Young** [comment]
Fixed 3 bugs for Upload CSV:

1. Bug 22: Upload CSV mobile: Pagination controls should be at bottom of the page 
2. Bug 39: Upload CSV preview box should be outlined in red if there is an error
3. Bug 42: Clicking Add to Map for mobile upload CSV view doesn’t open first accordion row with error

File: src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx [hunk 2]
```diff
@@ -316,60 +321,66 @@ const CSVViewTable = ({ rows, boxNumberMap }) => {
...
+                      </>
+                    )}
+                  </AccordionItem>
+                );
+              })}
+            </Flex>
+          </Accordion>
+        </div>
       )}
       <CSVViewTablePagination
```
Comment (claudeisakeeb) [inline src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx:360]: Bit of a nit but the pagination controls are still hovering for me: 
image

You can try giving the controller position sticky and then calculate the height of the csv upload table with something like calc(100vh - navBarHeight - tableHeaderHeight - paginationControllerHeight) so that it fills up the rest of the screen

**Review by claudeisakeeb — CHANGES_REQUESTED** [review]
Looks good :D 
Just one comment regarding the pagination controls hovering

File: src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx (hunk 2 above)
Comment (aliu55) [reply src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx:360]: genius

Comment (claudeisakeeb) [reply src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx:360]: no you

**Review by claudeisakeeb — DISMISSED** [review]
sicko mode

File: src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx [hunk 3]
```diff
@@ -316,59 +321,66 @@ const CSVViewTable = ({ rows, boxNumberMap }) => {
...
+          <Accordion {...accordionProps}>
+            <Flex flexDirection="column" gap="20px">
+              {page.map((rowData, index) => {
+                prepareRow(rowData);
+                return (
+                  <AccordionItem
+                    key={rowData.original.id}
+                    borderWidth="1px"
+                    borderRadius="8px"
+                    borderColor={rowData.values.error && 'red'}
```
Comment (meghakak) [inline src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx]: Can we use the warning color in [vars.css](https://github.com/ctc-uci/find-your-anchor-frontend/blob/dev/src/common/vars.css) instead of red?

File: src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx [hunk 4]
```diff
@@ -316,59 +321,66 @@ const CSVViewTable = ({ rows, boxNumberMap }) => {
...
+                  >
+                    {({ isExpanded }) => (
+                      <>
+                        <h2>
+                          <AccordionButton
+                            _expanded={{ bg: 'white' }}
```
Comment (meghakak) [inline src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx]: Same here, please use the colors in vars.css

**Review by meghakak — CHANGES_REQUESTED** [review]
LGTM for the most part! Just a couple comments on changing the hardcoded colors to use the colors defined in vars.css. While you will be changing all the colors in another style guide PR, it is better to start using the vars.css colors for any colors y'all add going forward.

**Review by claudeisakeeb — APPROVED** [review]
pog

**Review by meghakak — APPROVED** [review]
LGTM
