### PR TITLE
fix 3 admin approval process bugs pt 1

### LINKED ISSUE #80: Fix 3 Admin Approval Process Bugs Pt 1
Please fix bugs 2, 3, and 7 on the [dogfooding doc](https://docs.google.com/document/d/12VIkn9-iet9nRUiLaQjT_Y9oR2ggOaREwxJ4twXSYjo/edit#)

### PR DESCRIPTION
**Pull request by ctc-devops**
Please fix bugs 2, 3, and 7 on the [dogfooding doc](https://docs.google.com/document/d/12VIkn9-iet9nRUiLaQjT_Y9oR2ggOaREwxJ4twXSYjo/edit#)
closes #80

### CODE REVIEW

File: src/components/RelocationBox/RelocationBox.jsx [hunk 1]
```diff
@@ -89,6 +94,8 @@ const RelocationBox = ({
 
   // A function that approves a relocation box submission and updates the backend state accordingly and then refetches all boxes (boxes can be approved from any tab)
   const approveRelocationBox = async () => {
+    const user = await getCurrentUser(auth);
+    console.log(user);
```
Comment (ctc-devops) [inline src/components/RelocationBox/RelocationBox.jsx]: ⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

File: src/components/RelocationBox/RelocationBox.jsx [hunk 2]
```diff
@@ -153,6 +164,34 @@ const RelocationBox = ({
...
+      return RejectedRelocationIcon;
+    }
+    if (status === 'pending changes') {
+      return PendingRelocationIcon;
+    }
+    return RelocateBoxIcon;
+  };
+
+  // A function that creates the string that identifies which admin evaluated the box
+  const getStatusMessage = () => {
```
Comment (claudeisakeeb) [inline src/components/RelocationBox/RelocationBox.jsx:242]: Can we color these like in the figma?

One way you can do this is by moving the <\h4\> tags into the returns of this function and give each version a different class name. Also same thing for pick up boxes

File: src/components/BoxApproval/BoxApproval.jsx [hunk 3]
```diff
@@ -5,8 +5,8 @@ import PickupBox from '../PickupBox/PickupBox';
 import RelocationBox from '../RelocationBox/RelocationBox';
 import styles from './BoxApproval.module.css';
 import { FYABackend } from '../../common/utils';
-import PickupBoxIcon from '../BoxIcons/PickupBoxIcon.svg';
-import RelocateBoxIcon from '../BoxIcons/RelocateBoxIcon.svg';
+import PickupBoxIcon from '../../assets/BoxIcons/PickupBoxIcon.svg';
+import RelocateBoxIcon from '../../assets/BoxIcons/RelocateBoxIcon.svg';
 
 const BoxApproval = () => {
```
Comment (claudeisakeeb) [inline src/components/BoxApproval/BoxApproval.jsx:11]: I'm not sure if you get this bug but right now when I refresh the admin dashboard, click on pending changes, and then click on under review, box #1 shows up for a second before disappearing.

I believe you can fix this by not calling fetchBoxes(status, true) when status === 'pending changes' (line 91)

File: src/components/PickupBox/PickupBox.jsx [hunk 4]
```diff
@@ -68,6 +76,34 @@ const PickupBox = ({
     await fetchBoxes(status, true);
   };
 
+  // A function that changes the color of the relocation box icon depending on whether it's approved, rejected, pending, or not yet evaluated
+  const getColoredIcon = () => {
+    if (status === 'evaluated' && approved) {
+      return ApprovedPickupIcon;
+    }
+    if (status === 'evaluated' && approved === false) {
```
Comment (claudeisakeeb) [inline src/components/PickupBox/PickupBox.jsx]: super nit: you can shorten approved === false to !approved. Also please convert this to if else

File: src/components/PickupBox/PickupBox.jsx [hunk 5]
```diff
@@ -68,6 +76,34 @@ const PickupBox = ({
...
+      return RejectedPickupIcon;
+    }
+    if (status === 'pending changes') {
+      return PendingPickupIcon;
+    }
+    return PickupBoxIcon;
+  };
+
+  // A function that creates the string that identifies which admin evaluated the box
+  const getStatusMessage = () => {
```
Comment (claudeisakeeb) [inline src/components/PickupBox/PickupBox.jsx:103]: super nit: you can shorten approved === false to !approved. Also please convert this to if else

**Review by claudeisakeeb — CHANGES_REQUESTED** [review]
Good job, only a few nits and bugs to address

File: src/components/PickupBox/PickupBox.jsx (hunk 4 above)
Comment (meghakak) [reply src/components/PickupBox/PickupBox.jsx]: Eslint returns an error when we do if else here because we are returning something for each condition. Same with getStatusMessage.

File: src/components/PickupBox/PickupBox.jsx (hunk 5 above)
Comment (merylmarasigan) [reply src/components/PickupBox/PickupBox.jsx:103]: fixed!

File: src/components/PickupBox/PickupBox.jsx (hunk 4 above)
Comment (merylmarasigan) [reply src/components/PickupBox/PickupBox.jsx]: this has been fixed!

File: src/components/RelocationBox/RelocationBox.jsx (hunk 2 above)
Comment (merylmarasigan) [reply src/components/RelocationBox/RelocationBox.jsx:242]: fixed!

File: src/components/BoxApproval/BoxApproval.jsx (hunk 3 above)
Comment (merylmarasigan) [reply src/components/BoxApproval/BoxApproval.jsx:11]: this has been fixed!

**Review by claudeisakeeb — APPROVED** [review]
cut the check

**Review by sylvesteryue — APPROVED** [review]
LGTM
